<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net462</TargetFramework>
		<OutputType>Library</OutputType>
		<RootNamespace>NUnit.Extensions.Forms</RootNamespace>
		<LangVersion>latest</LangVersion>
		<DelaySign>false</DelaySign>
		<IsWebBootstrapper>false</IsWebBootstrapper>
		<PublishUrl>publish\</PublishUrl>
		<Install>true</Install>
		<InstallFrom>Disk</InstallFrom>
		<UpdateEnabled>false</UpdateEnabled>
		<UpdateMode>Foreground</UpdateMode>
		<UpdateInterval>7</UpdateInterval>
		<UpdateIntervalUnits>Days</UpdateIntervalUnits>
		<UpdatePeriodically>false</UpdatePeriodically>
		<UpdateRequired>false</UpdateRequired>
		<MapFileExtensions>true</MapFileExtensions>
		<ApplicationRevision>0</ApplicationRevision>
		<ApplicationVersion>1.0.0.%2a</ApplicationVersion>
		<UseApplicationTrust>false</UseApplicationTrust>
		<BootstrapperEnabled>true</BootstrapperEnabled>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<UseWindowsForms>true</UseWindowsForms>
		<ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
		<CodeAnalysisRules></CodeAnalysisRules>
		<CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
		<DocumentationFile>NUnitForms.xml</DocumentationFile>
		<RunCodeAnalysis>false</RunCodeAnalysis>
		<NoWarn>1591</NoWarn>
		<CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
		<DocumentationFile>NUnitForms.xml</DocumentationFile>
		<RunCodeAnalysis>false</RunCodeAnalysis>
		<NoWarn>1591</NoWarn>
		<CodeAnalysisRuleSet>AllRules.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="NUnit" Version="4.6.1" />
	</ItemGroup>
</Project>