# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build and Test

on:
  push: # all
  pull_request: # all

jobs:
  build:

    runs-on: windows-latest
    permissions: write-all
      # packages: write
      # contents: read

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v4
      with:
          nuget-version: 'latest'

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v3
      with:
        msbuild-architecture: x64

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: | 
          6.x
          8.x
          10.x
        # Authenticates packages to push to GPR
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Restore dependencies
      run: dotnet restore NUnitForms.slnx
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}

    - name: Build
      run: dotnet build NUnitForms.slnx --configuration Release --no-restore
      
    - name: Test
      run: dotnet test NUnitForms.slnx --configuration Release --no-build --verbosity normal
