# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Publish Release

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    permissions: write-all
      # packages: write
      # contents: read

    steps:
    - uses: actions/checkout@v6
      with:
        # lfs: true
        fetch-depth: 0

    - name: Setup Visual Studio
      uses: microsoft/setup-msbuild@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        # 4.6.x
        # 4.8.x
        dotnet-version: | 
          6.x
          8.x
          10.x
        # Authenticates packages to push to GPR
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Restore dependencies
      run: dotnet restore NUnitForms.slnx
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}

    - name: Build
      run: dotnet build NUnitForms.slnx --configuration Release --no-restore

    # - name: Test
    #   run: dotnet test NUnitForms.slnx --no-build --configuration Release --verbosity normal

    - name: Pack
      run: dotnet pack "NUnitForms/NUnitForms.csproj" --no-build --configuration Release

    - name: PushGithub
      run: dotnet nuget push **/*.nupkg --no-symbols --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: PushNuget
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUnitForms_Publish }} --skip-duplicate

