# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Publish Beta

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    permissions: write-all
      # packages: write
      # contents: read


    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        #ref: 'main'

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v4
      with:
          nuget-version: 'latest'

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v3
      with:
        msbuild-architecture: x64

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        # 4.6.x
        # 4.8.x
        dotnet-version: | 
          6.x
          8.x
          10.x
        # Authenticates packages to push to GPR
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Restore dependencies
      run: dotnet restore NUnitForms.slnx
      env:
        NUGET_AUTH_TOKEN: ${{ github.token }}

    - name: Build
      run: dotnet build NUnitForms.slnx --configuration Release --no-restore

    # - name: Test  is done in the "Build and Test" github workflow
    #   run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Pack
      run: dotnet pack "NUnitForms/NUnitForms.csproj" --no-build --configuration Release --version-suffix Beta

    - name: PushGithub
      run: dotnet nuget push **/*.nupkg --no-symbols --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: PushNuget
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUnitForms_Publish }} --skip-duplicate

